# Generated by Django 5.0.4 on 2024-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="irisModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sepal_length", models.FloatField(blank=True, default=0)),
                ("sepal_width", models.FloatField(blank=True, default=0)),
                ("petal_length", models.FloatField(blank=True, default=0)),
                ("petal_width", models.FloatField(blank=True, default=0)),
                ("species", models.CharField(blank=True, default="", max_length=30)),
            ],
        ),
    ]
